package types

type F10Data struct {
	Jbzl struct {
		Gsmc    string `json:"gsmc"`
		Ywmc    string `json:"ywmc"`
		Cym     string `json:"cym"`
		Agdm    string `json:"agdm"`
		Agjc    string `json:"agjc"`
		Bgdm    string `json:"bgdm"`
		Bgjc    string `json:"bgjc"`
		Hgdm    string `json:"hgdm"`
		Hgjc    string `json:"hgjc"`
		Zqlb    string `json:"zqlb"`
		Sshy    string `json:"sshy"`
		Ssjys   string `json:"ssjys"`
		Sszjhhy string `json:"sszjhhy"`
		Zjl     string `json:"zjl"`
		Frdb    string `json:"frdb"`
		Dm      string `json:"dm"`
		Dsz     string `json:"dsz"`
		Zqswdb  string `json:"zqswdb"`
		Dlds    string `json:"dlds"`
		Lxdh    string `json:"lxdh"`
		Dzxx    string `json:"dzxx"`
		Cz      string `json:"cz"`
		Gswz    string `json:"gswz"`
		Bgdz    string `json:"bgdz"`
		Zcdz    string `json:"zcdz"`
		Qy      string `json:"qy"`
		Yzbm    string `json:"yzbm"`
		Zczb    string `json:"zczb"`
		Gsdj    string `json:"gsdj"`
		Gyrs    string `json:"gyrs"`
		Glryrs  string `json:"glryrs"`
		Lssws   string `json:"lssws"`
		Kjssws  string `json:"kjssws"`
		Gsjj    string `json:"gsjj"`
		Jyfw    string `json:"jyfw"`
	} `json:"jbzl"`
	Fxxg struct {
		Clrq    string `json:"clrq"`
		Ssrq    string `json:"ssrq"`
		Fxsyl   string `json:"fxsyl"`
		Wsfxrq  string `json:"wsfxrq"`
		Fxfs    string `json:"fxfs"`
		Mgmz    string `json:"mgmz"`
		Fxl     string `json:"fxl"`
		Mgfxj   string `json:"mgfxj"`
		Fxfy    string `json:"fxfy"`
		Fxzsz   string `json:"fxzsz"`
		Mjzjje  string `json:"mjzjje"`
		Srkpj   string `json:"srkpj"`
		Srspj   string `json:"srspj"`
		Srhsl   string `json:"srhsl"`
		Srzgj   string `json:"srzgj"`
		Wxpszql string `json:"wxpszql"`
		Djzql   string `json:"djzql"`
	} `json:"fxxg"`
	Code              string      `json:"Code"`
	Codetype          string      `json:"CodeType"`
	Secucode          string      `json:"SecuCode"`
	Securitycode      string      `json:"SecurityCode"`
	Securityshortname string      `json:"SecurityShortName"`
	Marketcode        string      `json:"MarketCode"`
	Market            string      `json:"Market"`
	Securitytype      interface{} `json:"SecurityType"`
	Expiretime        string      `json:"ExpireTime"`
}
